### ISSUE TITLE
Questions about training speed

### ISSUE THREAD

**Issue by Keep-git** [m-kruse98/SplatPose#1]
Hi, I am a beginner, I render at the same speed on 3070 and 3090. I saw a maximum utilization of less than 50% on the 3090. How to solve this problem?

**Comment by m-kruse98** [comment]
Hey, thanks for the question. 

Since the Lego objects do not need as many Gaussians as very big scenes would, 50% of your VRAM is enough to fit the entire object.
As of now, the official 3DGS renderer does not support batching and only renders one image at a time, which means we can only utilize this much of the card and not more. Increasing the degree of spherical harmonics (currently 0, but 3 is possible), or the increasing image sizes would probably increase the workload for the card.

As for the speed: both cards are probably able to fit the entire scene and also use the same processor architecture. This may lead to them having the same speed, although I am guessing here.
